export const CONE_DEG = Number(process.env.CONE_DEG || 20);
export const SOFT_MAX_PEAK = Number(process.env.SOFT_MAX_PEAK || 15);
export const MID_MAX_PEAK = Number(process.env.MID_MAX_PEAK || 28);
export const MIN_PEAK = Number(process.env.MIN_PEAK || 8);
export const SOFT_MAX_KM = Number(process.env.SOFT_MAX_KM || 250);
export const MID_MAX_KM = Number(process.env.MID_MAX_KM || 3000);
export const REMINDER_1_MIN = Number(process.env.REMINDER_1_MIN || 45);
export const LOOSE_MIN = Number(process.env.LOOSE_MIN || 90);
export const BOUNCE_MIN = Number(process.env.BOUNCE_MIN || 120);
export const HOLD_HOURS = Number(process.env.HOLD_HOURS || 12);
export const LIVENESS_DAYS = Number(process.env.LIVENESS_DAYS || 14);
export const LIVENESS_GRACE_DAYS = Number(process.env.LIVENESS_GRACE_DAYS || 7);
export const INDEX_MAX_BLOCKS = Number(process.env.INDEX_MAX_BLOCKS || 20);
export const RECENT_HOLDERS_EXCLUDED = Number(process.env.RECENT_HOLDERS_EXCLUDED || 5);

export const DATABASE_URL = process.env.DATABASE_URL;
export const HIVE_API = process.env.HIVE_API || 'https://api.hive.blog';
export const THEBALL_ACCOUNT = process.env.THEBALL_ACCOUNT || 'theball';
export const THEBALL_POSTING_WIF = process.env.THEBALL_POSTING_WIF;
export const THEBALL_ACTIVE_WIF = process.env.THEBALL_ACTIVE_WIF;
export const TICK_SECRET = process.env.TICK_SECRET;
export const ADMIN_SECRET = process.env.ADMIN_SECRET;
export const SPAWN_BLOCK = Number(process.env.SPAWN_BLOCK || 0);
export const CHAIN_ID = Buffer.from(process.env.CHAIN_ID || '0000000000000000000000000000000000000000000000000000000000000000', 'hex'); // Default mainnet zero-chain-id is not actually zero, dhive defaults to it when not specified, but let's keep it simple.
